stages:
  - build
  - deploy

variables:
  DEV_DEPLOY_DIR: '/var/www/$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME/www-$CI_COMMIT_REF_NAME'
  VENDOR_DIRS: 'vendor'
  EXCLUDE_DIRS: '.git .idea tests'

before_script:
  - for DIR in $VENDOR_DIRS; do mkdir -p ../$DIR && rm -rf $DIR && mv ../$DIR .; done

after_script:
  - for DIR in $VENDOR_DIRS; do mv $DIR/ ../; done

build:
  stage: build
  only:
    - master
  artifacts:
    paths:
      - public/*.*
      - public/assets/bundle-*
  script:
    - composer --no-interaction --no-progress --prefer-dist install
    - echo "$CI_COMMIT_REF_NAME-$CI_JOB_ID" > $CI_PROJECT_DIR/public/version.txt

deploy_dev:
  stage: deploy
  only:
    - master
  script:
    - ssh root@dev "mkdir -p $DEV_DEPLOY_DIR"
    - printf "%s\n" $EXCLUDE_DIRS > ../.rsync-exclude && rsync -rzak --exclude-from=../.rsync-exclude $CI_PROJECT_DIR/ root@dev:$DEV_DEPLOY_DIR
    - ssh root@dev "cd $DEV_DEPLOY_DIR
      && ln -sf ../config/config.php
      && php yii migrate --interactive=0
      && service php7.3-fpm restart"
